/********************************************************************
* MyClass_RootDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error MyClass_RootDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableMyClass_RootDict();
extern void G__cpp_setup_inheritanceMyClass_RootDict();
extern void G__cpp_setup_typetableMyClass_RootDict();
extern void G__cpp_setup_memvarMyClass_RootDict();
extern void G__cpp_setup_globalMyClass_RootDict();
extern void G__cpp_setup_memfuncMyClass_RootDict();
extern void G__cpp_setup_funcMyClass_RootDict();
extern void G__set_cpp_environmentMyClass_RootDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MyClass.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__MyClass_RootDictLN_string;
extern G__linked_taginfo G__MyClass_RootDictLN_basic_stringstreamlEcharcOchar_traitslEchargRcOallocatorlEchargRsPgR;
extern G__linked_taginfo G__MyClass_RootDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__MyClass_RootDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MyClass_RootDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__MyClass_RootDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MyClass_RootDictLN_MyClass;

/* STUB derived class for protected member access */
